changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - skip-changelog
    authors:
      - dependabot
      - github-actions[bot]
      - renovate[bot]

  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - feat

    - title: Bug Fixes
      labels:
        - bug
        - fix
        - bugfix

    - title: Documentation
      labels:
        - documentation
        - docs
        - doc

    - title: Tests
      labels:
        - test
        - tests

    - title: Performance
      labels:
        - performance
        - perf

    - title: Maintenance
      labels:
        - chore
        - refactor
        - ci
        - build

    - title: Other Changes
      labels:
        - "*"
