repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: spdx-header-check
        name: Check SPDX Headers
        entry: uv run license --fix Apache-2.0 "Bruno Bernard"
        language: system
        files: (\.(py))$
        pass_filenames: true
        stages: [pre-commit]

      - id: ruff
        name: Run Ruff
        entry: uv run ruff check --fix
        language: system
        files: (\.(py))$
        pass_filenames: true
        stages: [pre-commit]
  - repo: https://github.com/eznix86/python-license
    rev: v1.0.1
    hooks:
      - id: license-headers
        args: ['--fix', 'Apache-2.0', 'Bruno Bernard']
