# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025  Bruno Bernard

"""Constants for file exclusion patterns."""

EXCLUDE_DIRS = {
    ".git",
    ".svn",
    ".hg",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "node_modules",
    "vendor",
    "third_party",
    "venv",
    ".venv",
    "env",
    ".env",
    "build",
    "dist",
    "target",
    "out",
    ".idea",
    ".vscode",
    ".vs",
    "dist",
    "target",
    "out",
    "bin",
    "public/build",
    "public/hot",
    ".air",
}

EXCLUDE_PATTERNS = {
    "*.min.js",
    "*.min.css",
    "*.generated.*",
    "*.pb.go",
    "*.pb.cc",
    "*_pb2.py",
    "*.log",
    "*.lock",
    "*.sum",
    "*.json",
    "*.toml",
    "*.yml",
    "*.yaml",
    "*.md",
    "*.svg",
    "*.sh",
    "LICENSE",
    "NOTICE",
    ".gitkeep",
    ".gitignore",
    ".licenseignore",
    ".go-version",
    "go.mod",
    ".pre-commit-config.yaml",
    ".golangci.yml",
}
