name: Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-groups

      - name: Run tests
        run: uv run pytest

      - name: Build wheel
        run: uv build

      - name: Publish package
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/*
          body: |
            ## 📦 Installation

            ```bash
            pipx install python-license==${{ github.ref_name }}
            ```

            ## 📄 PyPI Package
            https://pypi.org/project/python-license/${{ github.ref_name }}/

            ---
